name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Generate TOC
        run: npm run toc
      - name: Format files
        run: npm run format
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
