package com.nationalpark.scout.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.nationalpark.scout.repository.ColonistRepository;
import com.nationalpark.scout.models.Colonist;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ColonistController {
  @Autowired // This means to get the bean called colonistRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ColonistRepository colonistRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewColonist (@RequestParam String name) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Colonist n = new Colonist();
    n.setName(name);
    colonistRepository.save(n);
    return "Saved";
  }
  
  @CrossOrigin
  @GetMapping(path="/all")
  public @ResponseBody Iterable<Colonist> getAllColonists() {
    // This returns a JSON or XML with the colonists
    return colonistRepository.findAll();
  }
}